/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/project-workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Project Workspaces */
        get: operations["list_project_workspaces_api_project_workspaces_get"];
        put?: never;
        /** Create Project Workspace */
        post: operations["create_project_workspace_api_project_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/purchase-lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Workspace Purchase Lines */
        get: operations["get_project_workspace_purchase_lines_api_project_workspaces__project_workspace_id__purchase_lines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/manual-source-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Manual Source Entry */
        post: operations["create_manual_source_entry_api_project_workspaces__project_workspace_id__manual_source_entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/processing-jobs/{processing_job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Processing Job */
        get: operations["get_processing_job_api_project_workspaces__project_workspace_id__processing_jobs__processing_job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/taxonomy-nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Taxonomy Nodes */
        get: operations["list_taxonomy_nodes_api_project_workspaces__project_workspace_id__taxonomy_nodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/taxonomy-nodes/{taxonomy_node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Taxonomy Node */
        patch: operations["update_taxonomy_node_api_project_workspaces__project_workspace_id__taxonomy_nodes__taxonomy_node_id__patch"];
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/review-batches/{review_batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review Batch */
        get: operations["get_review_batch_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/review-batches/{review_batch_id}/candidates/{candidate_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Candidate */
        post: operations["decide_candidate_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__candidates__candidate_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/review-batches/{review_batch_id}/taxonomy-decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Taxonomy Decision */
        post: operations["create_taxonomy_decision_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__taxonomy_decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/review-batches/{review_batch_id}/duplicate-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Duplicate Group */
        post: operations["create_duplicate_group_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__duplicate_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/review-batches/{review_batch_id}/duplicate-groups/{duplicate_group_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Duplicate Group Members */
        post: operations["update_duplicate_group_members_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__duplicate_groups__duplicate_group_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/review-batches/{review_batch_id}/close-with-no-import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Review Batch No Import */
        post: operations["close_review_batch_no_import_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__close_with_no_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/review-batches/{review_batch_id}/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Review Batch */
        post: operations["import_review_batch_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CandidateDecisionRequest */
        CandidateDecisionRequest: {
            /** Decision */
            decision: ("approved" | "rejected" | "merged") | null;
            reviewed_payload?: components["schemas"]["ReviewedPurchaseLinePayload"] | null;
            /** Merged Into Candidate Id */
            merged_into_candidate_id?: number | null;
        };
        /** DuplicateCandidateGroupCreate */
        DuplicateCandidateGroupCreate: {
            /** Member Candidate Ids */
            member_candidate_ids: number[];
        };
        /** DuplicateCandidateGroupMembersRequest */
        DuplicateCandidateGroupMembersRequest: {
            /** Add Candidate Ids */
            add_candidate_ids?: number[];
            /** Remove Candidate Ids */
            remove_candidate_ids?: number[];
        };
        /** DuplicateCandidateGroupRead */
        DuplicateCandidateGroupRead: {
            /** Id */
            id: number;
            /** Project Workspace Id */
            project_workspace_id: number;
            /** Review Batch Id */
            review_batch_id: number;
            /** Member Candidate Ids */
            member_candidate_ids: number[];
        };
        /** ExtractedCandidateRead */
        ExtractedCandidateRead: {
            /** Id */
            id: number;
            /** Project Workspace Id */
            project_workspace_id: number;
            /** Review Batch Id */
            review_batch_id: number;
            /** Source Submission Id */
            source_submission_id: number;
            /** Status */
            status: string;
            /** Proposed Payload */
            proposed_payload: {
                [key: string]: unknown;
            };
            /** Decision */
            decision: string | null;
            /** Merged Into Candidate Id */
            merged_into_candidate_id: number | null;
            /** Reviewed Payload */
            reviewed_payload: {
                [key: string]: unknown;
            } | null;
            taxonomy_gate?: components["schemas"]["TaxonomyGateRead"] | null;
            taxonomy_default?: components["schemas"]["TaxonomyDefaultRead"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportReviewBatchResponse */
        ImportReviewBatchResponse: {
            /** Imported Purchase Lines */
            imported_purchase_lines: components["schemas"]["ImportedPurchaseLine"][];
        };
        /** ImportedPurchaseLine */
        ImportedPurchaseLine: {
            /** Id */
            id: number;
        };
        /** ManualSourceEntryCreate */
        ManualSourceEntryCreate: {
            /**
             * Entry Type
             * @enum {string}
             */
            entry_type: "structured_row" | "free_form_text";
            structured_payload?: components["schemas"]["StructuredManualSourcePayload"] | null;
            /** Original Text */
            original_text?: string | null;
        };
        /** ManualSourceEntryRead */
        ManualSourceEntryRead: {
            /** Id */
            id: number;
            /** Project Workspace Id */
            project_workspace_id: number;
            /** Source Submission Id */
            source_submission_id: number;
            /** Entry Type */
            entry_type: string;
            /** Structured Payload */
            structured_payload: {
                [key: string]: unknown;
            } | null;
            /** Original Text */
            original_text: string | null;
        };
        /** ManualSourceEntrySubmission */
        ManualSourceEntrySubmission: {
            source_submission: components["schemas"]["SourceSubmissionRead"];
            manual_source_entry: components["schemas"]["ManualSourceEntryRead"];
            processing_job: components["schemas"]["ProcessingJobRead"];
            review_batch: components["schemas"]["ReviewBatchRead"] | null;
            /** Candidates */
            candidates: components["schemas"]["ExtractedCandidateRead"][];
        };
        /** ProcessingJobDetail */
        ProcessingJobDetail: {
            processing_job: components["schemas"]["ProcessingJobRead"];
            source_submission: components["schemas"]["SourceSubmissionSummary"];
            /** Review Batch Id */
            review_batch_id: number | null;
        };
        /** ProcessingJobRead */
        ProcessingJobRead: {
            /** Id */
            id: number;
            /** Project Workspace Id */
            project_workspace_id: number;
            /** Source Submission Id */
            source_submission_id: number;
            /** Status */
            status: string;
            /** Source Type */
            source_type: string;
            /** Processor Name */
            processor_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Error Message */
            error_message: string | null;
            /** Candidate Count */
            candidate_count: number;
            /** Review Batch Id */
            review_batch_id: number | null;
        };
        /** ProjectWorkspaceCreate */
        ProjectWorkspaceCreate: {
            /** Project Name */
            project_name: string;
            /** Project Type */
            project_type: string;
            /** Location */
            location: string;
            /** Completion Date */
            completion_date?: string | null;
            /** Completion Year */
            completion_year?: number | null;
            /** Floor Area */
            floor_area?: string | null;
            /** Trade Scopes */
            trade_scopes?: string[];
            /** Client Or Owner */
            client_or_owner?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** ProjectWorkspaceList */
        ProjectWorkspaceList: {
            /** Items */
            items: components["schemas"]["ProjectWorkspaceListItem"][];
        };
        /** ProjectWorkspaceListItem */
        ProjectWorkspaceListItem: {
            /** Id */
            id: number;
            /** Project Name */
            project_name: string;
        };
        /** ProjectWorkspacePurchaseLinesView */
        ProjectWorkspacePurchaseLinesView: {
            project_workspace: components["schemas"]["ProjectWorkspaceListItem"];
            /** Items */
            items: components["schemas"]["PurchaseLineRow"][];
        };
        /** ProjectWorkspaceRead */
        ProjectWorkspaceRead: {
            /** Project Name */
            project_name: string;
            /** Project Type */
            project_type: string;
            /** Location */
            location: string;
            /** Completion Date */
            completion_date?: string | null;
            /** Completion Year */
            completion_year?: number | null;
            /** Floor Area */
            floor_area?: string | null;
            /** Trade Scopes */
            trade_scopes?: string[];
            /** Client Or Owner */
            client_or_owner?: string | null;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
        };
        /** PurchaseLineRow */
        PurchaseLineRow: {
            /** Id */
            id: number;
            /** Item Or Service Name */
            item_or_service_name: string;
            /** Line Type */
            line_type: string;
            /** Provider Name */
            provider_name: string | null;
            /** Provider Type */
            provider_type: string;
            /** Provider Role */
            provider_role: string | null;
            /** Quantity */
            quantity: string | null;
            /** Unit */
            unit: string | null;
            /** Unit State */
            unit_state: string;
            /** Price */
            price: string | null;
            /** Currency */
            currency: string | null;
            /** Price State */
            price_state: string;
            /** Purchase Date */
            purchase_date: string | null;
            /** Date State */
            date_state: string;
            /** Category Path */
            category_path: string;
            /** Has Evidence */
            has_evidence: boolean;
            /** Source Label */
            source_label: string;
        };
        /** ReviewBatchDetail */
        ReviewBatchDetail: {
            review_batch: components["schemas"]["ReviewBatchRead"];
            /** Candidates */
            candidates: components["schemas"]["ExtractedCandidateRead"][];
            /** Duplicate Groups */
            duplicate_groups?: components["schemas"]["DuplicateCandidateGroupRead"][];
            /** Duplicate Conflicts */
            duplicate_conflicts?: string[];
            /** Taxonomy Decisions */
            taxonomy_decisions?: components["schemas"]["TaxonomyDecisionRead"][];
        };
        /** ReviewBatchRead */
        ReviewBatchRead: {
            /** Id */
            id: number;
            /** Project Workspace Id */
            project_workspace_id: number;
            /** Source Submission Id */
            source_submission_id: number;
            /** Status */
            status: string;
        };
        /** ReviewedPurchaseLinePayload */
        ReviewedPurchaseLinePayload: {
            /** Line Type */
            line_type?: ("material" | "service") | null;
            /** Name */
            name?: string | null;
            /** Top Level Category */
            top_level_category?: string | null;
            /** Subcategory */
            subcategory?: string | null;
            /** Quantity */
            quantity?: string | null;
            /** Unit */
            unit?: string | null;
            /** Price */
            price?: string | null;
            /** Currency */
            currency?: string | null;
            /** Provider Name */
            provider_name?: string | null;
            /** Purchase Date */
            purchase_date?: string | null;
            /** Remarks Or Terms */
            remarks_or_terms?: string | null;
        };
        /** SourceSubmissionRead */
        SourceSubmissionRead: {
            /** Id */
            id: number;
            /** Project Workspace Id */
            project_workspace_id: number;
            /** Submission Type */
            submission_type: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Entered By */
            entered_by: {
                [key: string]: unknown;
            } | null;
        };
        /** SourceSubmissionSummary */
        SourceSubmissionSummary: {
            /** Id */
            id: number;
            /** Submission Type */
            submission_type: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
        };
        /** StructuredManualSourcePayload */
        StructuredManualSourcePayload: {
            /**
             * Line Type
             * @enum {string}
             */
            line_type: "material" | "service";
            /** Name */
            name: string;
            /** Quantity */
            quantity?: string | null;
            /** Unit */
            unit?: string | null;
            /** Price */
            price?: string | null;
            /** Currency */
            currency?: string | null;
            /** Provider Name */
            provider_name?: string | null;
            /** Purchase Date */
            purchase_date?: string | null;
            /** Remarks Or Terms */
            remarks_or_terms?: string | null;
        };
        /** TaxonomyDecisionCreate */
        TaxonomyDecisionCreate: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "mapped" | "rejected";
            /** Suggested Top Level Category */
            suggested_top_level_category: string;
            /** Suggested Subcategory */
            suggested_subcategory?: string | null;
            /** Resolved Taxonomy Node Id */
            resolved_taxonomy_node_id?: number | null;
        };
        /** TaxonomyDecisionRead */
        TaxonomyDecisionRead: {
            /** Id */
            id: number;
            /** Project Workspace Id */
            project_workspace_id: number;
            /** Review Batch Id */
            review_batch_id: number;
            /** Suggested Top Level Category */
            suggested_top_level_category: string;
            /** Suggested Subcategory */
            suggested_subcategory: string | null;
            /** Normalized Suggested Path Key */
            normalized_suggested_path_key: string;
            /** Decision */
            decision: string;
            /** Resolved Taxonomy Node Id */
            resolved_taxonomy_node_id: number | null;
        };
        /** TaxonomyDefaultRead */
        TaxonomyDefaultRead: {
            /** Resolved Category Path */
            resolved_category_path: string;
            /** Source */
            source: string;
            /** Provenance Text */
            provenance_text: string;
            /** Taxonomy Decision Id */
            taxonomy_decision_id: number;
        };
        /** TaxonomyGateRead */
        TaxonomyGateRead: {
            /** Status */
            status: string;
            /** Reason */
            reason?: string | null;
            /** Suggested Category Path */
            suggested_category_path: string;
            /** Resolved Category Path */
            resolved_category_path?: string | null;
            /** Decision */
            decision?: string | null;
            /** Taxonomy Decision Id */
            taxonomy_decision_id?: number | null;
            /** Prior Rejection */
            prior_rejection?: {
                [key: string]: unknown;
            } | null;
        };
        /** TaxonomyNodeListRead */
        TaxonomyNodeListRead: {
            /** Items */
            items: components["schemas"]["TaxonomyNodePathRead"][];
        };
        /** TaxonomyNodePathRead */
        TaxonomyNodePathRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id: number | null;
            /** Path */
            path: string;
        };
        /** TaxonomyNodeUpdate */
        TaxonomyNodeUpdate: {
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_project_workspaces_api_project_workspaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectWorkspaceList"];
                };
            };
        };
    };
    create_project_workspace_api_project_workspaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectWorkspaceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectWorkspaceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_workspace_purchase_lines_api_project_workspaces__project_workspace_id__purchase_lines_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectWorkspacePurchaseLinesView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_manual_source_entry_api_project_workspaces__project_workspace_id__manual_source_entries_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualSourceEntryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualSourceEntrySubmission"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_processing_job_api_project_workspaces__project_workspace_id__processing_jobs__processing_job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
                processing_job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingJobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_taxonomy_nodes_api_project_workspaces__project_workspace_id__taxonomy_nodes_get: {
        parameters: {
            query?: {
                leaf_only?: boolean;
            };
            header?: never;
            path: {
                project_workspace_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyNodeListRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_taxonomy_node_api_project_workspaces__project_workspace_id__taxonomy_nodes__taxonomy_node_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
                taxonomy_node_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaxonomyNodeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyNodePathRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_batch_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
                review_batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewBatchDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_candidate_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__candidates__candidate_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
                review_batch_id: number;
                candidate_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractedCandidateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_taxonomy_decision_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__taxonomy_decisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
                review_batch_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaxonomyDecisionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewBatchDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_duplicate_group_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__duplicate_groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
                review_batch_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DuplicateCandidateGroupCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateCandidateGroupRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_duplicate_group_members_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__duplicate_groups__duplicate_group_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
                review_batch_id: number;
                duplicate_group_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DuplicateCandidateGroupMembersRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateCandidateGroupRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_review_batch_no_import_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__close_with_no_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
                review_batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewBatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_review_batch_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
                review_batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportReviewBatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
