/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/project-workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Project Workspaces */
        get: operations["list_project_workspaces_api_project_workspaces_get"];
        put?: never;
        /** Create Project Workspace */
        post: operations["create_project_workspace_api_project_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/purchase-lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Workspace Purchase Lines */
        get: operations["get_project_workspace_purchase_lines_api_project_workspaces__project_workspace_id__purchase_lines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Workspace Materials */
        get: operations["get_project_workspace_materials_api_project_workspaces__project_workspace_id__materials_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/services": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Workspace Services */
        get: operations["get_project_workspace_services_api_project_workspaces__project_workspace_id__services_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Workspace Providers */
        get: operations["get_project_workspace_providers_api_project_workspaces__project_workspace_id__providers_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/source-files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Source File */
        post: operations["create_source_file_api_project_workspaces__project_workspace_id__source_files_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/manual-source-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Manual Source Entry */
        post: operations["create_manual_source_entry_api_project_workspaces__project_workspace_id__manual_source_entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/processing-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Processing Jobs */
        get: operations["list_processing_jobs_api_project_workspaces__project_workspace_id__processing_jobs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/processing-jobs/{processing_job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Processing Job */
        get: operations["get_processing_job_api_project_workspaces__project_workspace_id__processing_jobs__processing_job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/taxonomy-nodes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Taxonomy Nodes */
        get: operations["list_taxonomy_nodes_api_project_workspaces__project_workspace_id__taxonomy_nodes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/taxonomy-nodes/{taxonomy_node_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Taxonomy Node */
        patch: operations["update_taxonomy_node_api_project_workspaces__project_workspace_id__taxonomy_nodes__taxonomy_node_id__patch"];
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/review-batches/{review_batch_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Review Batch */
        get: operations["get_review_batch_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/review-batches/{review_batch_id}/candidates/{candidate_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Candidate */
        post: operations["decide_candidate_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__candidates__candidate_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/review-batches/{review_batch_id}/taxonomy-gates/{taxonomy_gate_id}/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Accept Taxonomy Gate */
        post: operations["accept_taxonomy_gate_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__taxonomy_gates__taxonomy_gate_id__accept_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/review-batches/{review_batch_id}/taxonomy-gates/{taxonomy_gate_id}/reviewer-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Taxonomy Gate Reviewer Draft */
        put: operations["save_taxonomy_gate_reviewer_draft_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__taxonomy_gates__taxonomy_gate_id__reviewer_draft_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/review-batches/{review_batch_id}/taxonomy-gates/{taxonomy_gate_id}/selection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Select Taxonomy Gate Proposal */
        put: operations["select_taxonomy_gate_proposal_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__taxonomy_gates__taxonomy_gate_id__selection_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/review-batches/{review_batch_id}/taxonomy-gates/{taxonomy_gate_id}/edit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Edit Accepted Taxonomy Gate */
        post: operations["edit_accepted_taxonomy_gate_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__taxonomy_gates__taxonomy_gate_id__edit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/review-batches/{review_batch_id}/review-draft": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Review Batch Draft */
        put: operations["save_review_batch_draft_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__review_draft_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/review-batches/{review_batch_id}/taxonomy-decisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Taxonomy Decision */
        post: operations["create_taxonomy_decision_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__taxonomy_decisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/review-batches/{review_batch_id}/taxonomy-mappings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Save Review Batch Taxonomy Mapping */
        post: operations["save_review_batch_taxonomy_mapping_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__taxonomy_mappings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/review-batches/{review_batch_id}/duplicate-groups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Duplicate Group */
        post: operations["create_duplicate_group_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__duplicate_groups_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/review-batches/{review_batch_id}/duplicate-groups/{duplicate_group_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Update Duplicate Group Members */
        post: operations["update_duplicate_group_members_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__duplicate_groups__duplicate_group_id__members_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/review-batches/{review_batch_id}/close-with-no-import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Close Review Batch No Import */
        post: operations["close_review_batch_no_import_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__close_with_no_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/review-batches/{review_batch_id}/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Review Batch */
        post: operations["import_review_batch_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_create_source_file_api_project_workspaces__project_workspace_id__source_files_post */
        Body_create_source_file_api_project_workspaces__project_workspace_id__source_files_post: {
            /** Files */
            files: string[];
        };
        /** CandidateDecisionRequest */
        CandidateDecisionRequest: {
            /** Decision */
            decision: ("approved" | "rejected" | "merged") | null;
            reviewed_payload?: components["schemas"]["ReviewedPurchaseLinePayload"] | null;
            /** Merged Into Candidate Id */
            merged_into_candidate_id?: number | null;
        };
        /** CandidateTaxonomyGateRead */
        CandidateTaxonomyGateRead: {
            /** Status */
            status: string;
            /** Reason */
            reason?: string | null;
            /** Suggested Category Path */
            suggested_category_path: string;
            /** Resolved Category Path */
            resolved_category_path?: string | null;
            /** Decision */
            decision?: string | null;
            /** Taxonomy Decision Id */
            taxonomy_decision_id?: number | null;
            /** Prior Rejection */
            prior_rejection?: {
                [key: string]: unknown;
            } | null;
            /** Id */
            id: number;
            /** Active */
            active: boolean;
            /**
             * Subject Type
             * @enum {string}
             */
            subject_type: "material" | "service" | "provider";
            /** Subject Name */
            subject_name: string;
            /** Original Ai Category Path */
            original_ai_category_path: string;
            /** Reviewer Draft Category Path */
            reviewer_draft_category_path?: string | null;
            /**
             * Selected Proposal
             * @enum {string}
             */
            selected_proposal: "ai_suggestion" | "reviewer_draft";
            /** Selected Category Path */
            selected_category_path: string;
            /** Accepted Category Path */
            accepted_category_path?: string | null;
            /** Accepted Source */
            accepted_source?: ("ai_suggestion" | "reviewer_draft") | null;
            /** Decision History */
            decision_history?: components["schemas"]["TaxonomyDecisionRead"][];
        };
        /** DuplicateCandidateGroupCreate */
        DuplicateCandidateGroupCreate: {
            /** Member Candidate Ids */
            member_candidate_ids: number[];
        };
        /** DuplicateCandidateGroupMembersRequest */
        DuplicateCandidateGroupMembersRequest: {
            /** Add Candidate Ids */
            add_candidate_ids?: number[];
            /** Remove Candidate Ids */
            remove_candidate_ids?: number[];
        };
        /** DuplicateCandidateGroupRead */
        DuplicateCandidateGroupRead: {
            /** Id */
            id: number;
            /** Project Workspace Id */
            project_workspace_id: number;
            /** Review Batch Id */
            review_batch_id: number;
            /** Member Candidate Ids */
            member_candidate_ids: number[];
        };
        /** EntityMemoryListView */
        EntityMemoryListView: {
            project_workspace: components["schemas"]["ProjectWorkspaceListItem"];
            /** Items */
            items: components["schemas"]["EntityMemoryRow"][];
        };
        /** EntityMemoryRow */
        EntityMemoryRow: {
            /** Memory Record Id */
            memory_record_id: number;
            /** Name */
            name: string;
            /** Category Path */
            category_path: string;
            /** Linked Purchase Line Count */
            linked_purchase_line_count: number;
            /** Source Submission Count */
            source_submission_count: number;
        };
        /** ExistingMemoryMatchRead */
        ExistingMemoryMatchRead: {
            /**
             * Subject Type
             * @enum {string}
             */
            subject_type: "material" | "service" | "provider";
            /** Subject Name */
            subject_name: string;
            /** Category Path */
            category_path: string;
        };
        /** ExtractedCandidateRead */
        ExtractedCandidateRead: {
            /** Id */
            id: number;
            /** Project Workspace Id */
            project_workspace_id: number;
            /** Review Batch Id */
            review_batch_id: number;
            /** Source Submission Id */
            source_submission_id: number;
            /** Status */
            status: string;
            /** Proposed Payload */
            proposed_payload: {
                [key: string]: unknown;
            };
            /** Decision */
            decision: string | null;
            /** Merged Into Candidate Id */
            merged_into_candidate_id: number | null;
            /** Reviewed Payload */
            reviewed_payload: {
                [key: string]: unknown;
            } | null;
            source_file?: components["schemas"]["SourceFileSummary"] | null;
            taxonomy_gate?: components["schemas"]["TaxonomyGateRead"] | null;
            /** Taxonomy Gates */
            taxonomy_gates?: components["schemas"]["CandidateTaxonomyGateRead"][];
            /** Existing Memory Matches */
            existing_memory_matches?: components["schemas"]["ExistingMemoryMatchRead"][];
            taxonomy_default?: components["schemas"]["TaxonomyDefaultRead"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportReviewBatchResponse */
        ImportReviewBatchResponse: {
            /** Imported Purchase Lines */
            imported_purchase_lines: components["schemas"]["ImportedPurchaseLine"][];
        };
        /** ImportedPurchaseLine */
        ImportedPurchaseLine: {
            /** Id */
            id: number;
        };
        /** ManualSourceEntryCreate */
        ManualSourceEntryCreate: {
            /**
             * Entry Type
             * @enum {string}
             */
            entry_type: "structured_row" | "free_form_text";
            structured_payload?: components["schemas"]["StructuredManualSourcePayload"] | null;
            /** Original Text */
            original_text?: string | null;
        };
        /** ManualSourceEntryQueuedSubmission */
        ManualSourceEntryQueuedSubmission: {
            source_submission: components["schemas"]["SourceSubmissionRead"];
            manual_source_entry: components["schemas"]["ManualSourceEntryRead"];
            processing_job: components["schemas"]["ProcessingJobRead"];
        };
        /** ManualSourceEntryRead */
        ManualSourceEntryRead: {
            /** Id */
            id: number;
            /** Project Workspace Id */
            project_workspace_id: number;
            /** Source Submission Id */
            source_submission_id: number;
            /** Entry Type */
            entry_type: string;
            /** Structured Payload */
            structured_payload: {
                [key: string]: unknown;
            } | null;
            /** Original Text */
            original_text: string | null;
        };
        /** ProcessingJobDetail */
        ProcessingJobDetail: {
            processing_job: components["schemas"]["ProcessingJobRead"];
            source_submission: components["schemas"]["SourceSubmissionSummary"];
            source_file?: components["schemas"]["SourceFileSummary"] | null;
            /** Review Batch Id */
            review_batch_id: number | null;
        };
        /** ProcessingJobList */
        ProcessingJobList: {
            /** Items */
            items: components["schemas"]["ProcessingJobListItem"][];
        };
        /** ProcessingJobListItem */
        ProcessingJobListItem: {
            processing_job: components["schemas"]["ProcessingJobRead"];
            source_submission: components["schemas"]["SourceSubmissionSummary"];
            source_file?: components["schemas"]["SourceFileSummary"] | null;
            /** Review Batch Id */
            review_batch_id: number | null;
        };
        /** ProcessingJobRead */
        ProcessingJobRead: {
            /** Id */
            id: number;
            /** Project Workspace Id */
            project_workspace_id: number;
            /** Source Submission Id */
            source_submission_id: number;
            /** Status */
            status: string;
            /** Source Type */
            source_type: string;
            /** Processor Name */
            processor_name: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Started At */
            started_at: string | null;
            /** Finished At */
            finished_at: string | null;
            /** Error Message */
            error_message: string | null;
            /** Diagnostics */
            diagnostics: {
                [key: string]: unknown;
            } | null;
            /** Candidate Count */
            candidate_count: number;
            /** Review Batch Id */
            review_batch_id: number | null;
        };
        /** ProjectWorkspaceCreate */
        ProjectWorkspaceCreate: {
            /** Project Name */
            project_name: string;
            /** Project Type */
            project_type: string;
            /** Location */
            location: string;
            /** Completion Date */
            completion_date?: string | null;
            /** Completion Year */
            completion_year?: number | null;
            /** Floor Area */
            floor_area?: string | null;
            /** Trade Scopes */
            trade_scopes?: string[];
            /** Contractor Assigned */
            contractor_assigned: string;
            /** Client Or Owner */
            client_or_owner?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** ProjectWorkspaceList */
        ProjectWorkspaceList: {
            /** Items */
            items: components["schemas"]["ProjectWorkspaceListItem"][];
        };
        /** ProjectWorkspaceListItem */
        ProjectWorkspaceListItem: {
            /** Id */
            id: number;
            /** Project Name */
            project_name: string;
        };
        /** ProjectWorkspacePurchaseLinesView */
        ProjectWorkspacePurchaseLinesView: {
            project_workspace: components["schemas"]["ProjectWorkspaceListItem"];
            /** Items */
            items: components["schemas"]["PurchaseLineRow"][];
        };
        /** ProjectWorkspaceRead */
        ProjectWorkspaceRead: {
            /** Project Name */
            project_name: string;
            /** Project Type */
            project_type: string;
            /** Location */
            location: string;
            /** Completion Date */
            completion_date?: string | null;
            /** Completion Year */
            completion_year?: number | null;
            /** Floor Area */
            floor_area?: string | null;
            /** Trade Scopes */
            trade_scopes?: string[];
            /** Contractor Assigned */
            contractor_assigned: string;
            /** Client Or Owner */
            client_or_owner?: string | null;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
        };
        /** ProviderMemoryListView */
        ProviderMemoryListView: {
            project_workspace: components["schemas"]["ProjectWorkspaceListItem"];
            /** Items */
            items: components["schemas"]["ProviderMemoryRow"][];
        };
        /** ProviderMemoryRow */
        ProviderMemoryRow: {
            /** Memory Record Id */
            memory_record_id: number;
            /** Name */
            name: string;
            /** Category Path */
            category_path: string;
            /** Linked Purchase Line Count */
            linked_purchase_line_count: number;
            /** Source Submission Count */
            source_submission_count: number;
            /** Roles */
            roles: string[];
        };
        /** PurchaseLineConceptRead */
        PurchaseLineConceptRead: {
            /** Memory Record Id */
            memory_record_id: number;
            /** Concept Type */
            concept_type: string;
            /** Name */
            name: string;
            /** Category Path */
            category_path: string;
        };
        /** PurchaseLineRow */
        PurchaseLineRow: {
            /** Id */
            id: number;
            /** Line Type */
            line_type: string;
            /** Linked Concepts */
            linked_concepts: components["schemas"]["PurchaseLineConceptRead"][];
            /** Provider State */
            provider_state: string;
            /** Provider Name */
            provider_name: string | null;
            /** Provider Category Path */
            provider_category_path: string | null;
            /** Provider Roles */
            provider_roles: string[];
            /** Quantity */
            quantity: string | null;
            /** Unit */
            unit: string | null;
            /** Unit State */
            unit_state: string;
            /** Price */
            price: string | null;
            /** Currency */
            currency: string | null;
            /** Price State */
            price_state: string;
            /** Purchase Date */
            purchase_date: string | null;
            /** Date State */
            date_state: string;
            /** Has Evidence */
            has_evidence: boolean;
            /** Source Label */
            source_label: string;
        };
        /** ReviewBatchDetail */
        ReviewBatchDetail: {
            review_batch: components["schemas"]["ReviewBatchRead"];
            /** Candidates */
            candidates: components["schemas"]["ExtractedCandidateRead"][];
            /** Duplicate Groups */
            duplicate_groups?: components["schemas"]["DuplicateCandidateGroupRead"][];
            /** Duplicate Conflicts */
            duplicate_conflicts?: string[];
            /** Taxonomy Decisions */
            taxonomy_decisions?: components["schemas"]["TaxonomyDecisionRead"][];
        };
        /** ReviewBatchDraftCandidate */
        ReviewBatchDraftCandidate: {
            /** Candidate Id */
            candidate_id: number;
            /** Included */
            included: boolean;
            reviewed_payload?: components["schemas"]["ReviewedPurchaseLinePayload"] | null;
        };
        /** ReviewBatchDraftSaveRequest */
        ReviewBatchDraftSaveRequest: {
            /** Candidates */
            candidates: components["schemas"]["ReviewBatchDraftCandidate"][];
        };
        /** ReviewBatchRead */
        ReviewBatchRead: {
            /** Id */
            id: number;
            /** Project Workspace Id */
            project_workspace_id: number;
            /** Source Submission Id */
            source_submission_id: number;
            /** Status */
            status: string;
        };
        /** ReviewBatchTaxonomyMappingRequest */
        ReviewBatchTaxonomyMappingRequest: {
            /** Candidate Id */
            candidate_id: number;
            /** Top Level Category */
            top_level_category: string;
            /** Subcategory */
            subcategory: string;
            /**
             * Apply To Similar
             * @default false
             */
            apply_to_similar: boolean;
        };
        /** ReviewedConceptPayload */
        ReviewedConceptPayload: {
            /**
             * Concept Type
             * @enum {string}
             */
            concept_type: "material" | "service";
            /** Name */
            name?: string | null;
            /** Top Level Category */
            top_level_category?: string | null;
            /** Subcategory */
            subcategory?: string | null;
        };
        /** ReviewedPurchaseLinePayload */
        ReviewedPurchaseLinePayload: {
            /** Linked Concepts */
            linked_concepts?: components["schemas"]["ReviewedConceptPayload"][];
            /** Provider State */
            provider_state?: ("external" | "internal" | "unknown") | null;
            /** Provider Top Level Category */
            provider_top_level_category?: string | null;
            /** Provider Subcategory */
            provider_subcategory?: string | null;
            /** Line Type */
            line_type?: ("material" | "service") | null;
            /** Name */
            name?: string | null;
            /** Top Level Category */
            top_level_category?: string | null;
            /** Subcategory */
            subcategory?: string | null;
            /** Quantity */
            quantity?: string | null;
            /** Unit */
            unit?: string | null;
            /** Price */
            price?: string | null;
            /** Currency */
            currency?: string | null;
            /** Provider Name */
            provider_name?: string | null;
            /** Purchase Date */
            purchase_date?: string | null;
            /** Remarks Or Terms */
            remarks_or_terms?: string | null;
        };
        /** SourceFileQueuedSubmission */
        SourceFileQueuedSubmission: {
            source_submission: components["schemas"]["SourceSubmissionRead"];
            source_file: components["schemas"]["SourceFileRead"];
            processing_job: components["schemas"]["ProcessingJobRead"];
        };
        /** SourceFileRead */
        SourceFileRead: {
            /** Id */
            id: number;
            /** Project Workspace Id */
            project_workspace_id: number;
            /** Source Submission Id */
            source_submission_id: number;
            /** Original Filename */
            original_filename: string;
            /** Byte Size */
            byte_size: number;
            /** Declared Mime Type */
            declared_mime_type: string | null;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /** Sha256 Checksum */
            sha256_checksum: string;
            /** Storage Path */
            storage_path: string;
        };
        /** SourceFileSummary */
        SourceFileSummary: {
            /** Id */
            id: number;
            /** Original Filename */
            original_filename: string;
            /** Byte Size */
            byte_size: number;
            /** Declared Mime Type */
            declared_mime_type: string | null;
            /**
             * Uploaded At
             * Format: date-time
             */
            uploaded_at: string;
            /** Sha256 Checksum */
            sha256_checksum: string;
        };
        /** SourceSubmissionRead */
        SourceSubmissionRead: {
            /** Id */
            id: number;
            /** Project Workspace Id */
            project_workspace_id: number;
            /** Submission Type */
            submission_type: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
            /** Entered By */
            entered_by: {
                [key: string]: unknown;
            } | null;
        };
        /** SourceSubmissionSummary */
        SourceSubmissionSummary: {
            /** Id */
            id: number;
            /** Submission Type */
            submission_type: string;
            /**
             * Submitted At
             * Format: date-time
             */
            submitted_at: string;
        };
        /** StructuredManualSourcePayload */
        StructuredManualSourcePayload: {
            /**
             * Line Type
             * @enum {string}
             */
            line_type: "material" | "service";
            /** Name */
            name: string;
            /** Quantity */
            quantity?: string | null;
            /** Unit */
            unit?: string | null;
            /** Price */
            price?: string | null;
            /** Currency */
            currency?: string | null;
            /** Provider Name */
            provider_name?: string | null;
            /** Purchase Date */
            purchase_date?: string | null;
            /** Remarks Or Terms */
            remarks_or_terms?: string | null;
        };
        /** TaxonomyDecisionCreate */
        TaxonomyDecisionCreate: {
            /**
             * Decision
             * @enum {string}
             */
            decision: "approved" | "mapped" | "rejected";
            /** Suggested Top Level Category */
            suggested_top_level_category: string;
            /** Suggested Subcategory */
            suggested_subcategory?: string | null;
            /** Resolved Taxonomy Node Id */
            resolved_taxonomy_node_id?: number | null;
        };
        /** TaxonomyDecisionRead */
        TaxonomyDecisionRead: {
            /** Id */
            id: number;
            /** Project Workspace Id */
            project_workspace_id: number;
            /** Review Batch Id */
            review_batch_id: number;
            /** Suggested Top Level Category */
            suggested_top_level_category: string;
            /** Suggested Subcategory */
            suggested_subcategory: string | null;
            /** Normalized Suggested Path Key */
            normalized_suggested_path_key: string;
            /** Decision */
            decision: string;
            /** Resolved Taxonomy Node Id */
            resolved_taxonomy_node_id: number | null;
            /** Taxonomy Gate Id */
            taxonomy_gate_id?: number | null;
            /** Candidate Id */
            candidate_id?: number | null;
            /** Subject Type */
            subject_type?: string | null;
            /** Subject Name */
            subject_name?: string | null;
            /** Accepted Source */
            accepted_source?: string | null;
            /**
             * Superseded
             * @default false
             */
            superseded: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Superseded At */
            superseded_at?: string | null;
            /** Accepted Category Path */
            accepted_category_path?: string | null;
        };
        /** TaxonomyDefaultRead */
        TaxonomyDefaultRead: {
            /** Resolved Category Path */
            resolved_category_path: string;
            /** Source */
            source: string;
            /** Provenance Text */
            provenance_text: string;
            /** Taxonomy Decision Id */
            taxonomy_decision_id: number;
        };
        /** TaxonomyGateRead */
        TaxonomyGateRead: {
            /** Status */
            status: string;
            /** Reason */
            reason?: string | null;
            /** Suggested Category Path */
            suggested_category_path: string;
            /** Resolved Category Path */
            resolved_category_path?: string | null;
            /** Decision */
            decision?: string | null;
            /** Taxonomy Decision Id */
            taxonomy_decision_id?: number | null;
            /** Prior Rejection */
            prior_rejection?: {
                [key: string]: unknown;
            } | null;
        };
        /** TaxonomyGateReviewerDraftSaveRequest */
        TaxonomyGateReviewerDraftSaveRequest: {
            /** Top Level Category */
            top_level_category: string;
            /** Subcategory */
            subcategory: string;
            /**
             * Apply To Similar
             * @default false
             */
            apply_to_similar: boolean;
        };
        /** TaxonomyGateReviewerDraftSaveResponse */
        TaxonomyGateReviewerDraftSaveResponse: {
            review_batch: components["schemas"]["ReviewBatchDetail"];
            /** Affected Count */
            affected_count: number;
        };
        /** TaxonomyGateSelectionRequest */
        TaxonomyGateSelectionRequest: {
            /**
             * Selected Proposal
             * @enum {string}
             */
            selected_proposal: "ai_suggestion" | "reviewer_draft";
        };
        /** TaxonomyNodeListRead */
        TaxonomyNodeListRead: {
            /** Items */
            items: components["schemas"]["TaxonomyNodePathRead"][];
        };
        /** TaxonomyNodePathRead */
        TaxonomyNodePathRead: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Parent Id */
            parent_id: number | null;
            /** Path */
            path: string;
        };
        /** TaxonomyNodeUpdate */
        TaxonomyNodeUpdate: {
            /** Name */
            name: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_project_workspaces_api_project_workspaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectWorkspaceList"];
                };
            };
        };
    };
    create_project_workspace_api_project_workspaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectWorkspaceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectWorkspaceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_workspace_purchase_lines_api_project_workspaces__project_workspace_id__purchase_lines_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectWorkspacePurchaseLinesView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_workspace_materials_api_project_workspaces__project_workspace_id__materials_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityMemoryListView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_workspace_services_api_project_workspaces__project_workspace_id__services_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityMemoryListView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_workspace_providers_api_project_workspaces__project_workspace_id__providers_get: {
        parameters: {
            query?: {
                roles?: string[];
            };
            header?: never;
            path: {
                project_workspace_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProviderMemoryListView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_source_file_api_project_workspaces__project_workspace_id__source_files_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_create_source_file_api_project_workspaces__project_workspace_id__source_files_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceFileQueuedSubmission"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_manual_source_entry_api_project_workspaces__project_workspace_id__manual_source_entries_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManualSourceEntryCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ManualSourceEntryQueuedSubmission"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_processing_jobs_api_project_workspaces__project_workspace_id__processing_jobs_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingJobList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_processing_job_api_project_workspaces__project_workspace_id__processing_jobs__processing_job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
                processing_job_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProcessingJobDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_taxonomy_nodes_api_project_workspaces__project_workspace_id__taxonomy_nodes_get: {
        parameters: {
            query?: {
                leaf_only?: boolean;
            };
            header?: never;
            path: {
                project_workspace_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyNodeListRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_taxonomy_node_api_project_workspaces__project_workspace_id__taxonomy_nodes__taxonomy_node_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
                taxonomy_node_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaxonomyNodeUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyNodePathRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_review_batch_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
                review_batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewBatchDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_candidate_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__candidates__candidate_id__decision_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
                review_batch_id: number;
                candidate_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CandidateDecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractedCandidateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    accept_taxonomy_gate_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__taxonomy_gates__taxonomy_gate_id__accept_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
                review_batch_id: number;
                taxonomy_gate_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewBatchDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_taxonomy_gate_reviewer_draft_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__taxonomy_gates__taxonomy_gate_id__reviewer_draft_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
                review_batch_id: number;
                taxonomy_gate_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaxonomyGateReviewerDraftSaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaxonomyGateReviewerDraftSaveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    select_taxonomy_gate_proposal_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__taxonomy_gates__taxonomy_gate_id__selection_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
                review_batch_id: number;
                taxonomy_gate_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaxonomyGateSelectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewBatchDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_accepted_taxonomy_gate_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__taxonomy_gates__taxonomy_gate_id__edit_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
                review_batch_id: number;
                taxonomy_gate_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewBatchDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_review_batch_draft_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__review_draft_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
                review_batch_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewBatchDraftSaveRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewBatchDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_taxonomy_decision_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__taxonomy_decisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
                review_batch_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaxonomyDecisionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewBatchDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_review_batch_taxonomy_mapping_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__taxonomy_mappings_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
                review_batch_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReviewBatchTaxonomyMappingRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewBatchDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_duplicate_group_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__duplicate_groups_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
                review_batch_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DuplicateCandidateGroupCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateCandidateGroupRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_duplicate_group_members_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__duplicate_groups__duplicate_group_id__members_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
                review_batch_id: number;
                duplicate_group_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DuplicateCandidateGroupMembersRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DuplicateCandidateGroupRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    close_review_batch_no_import_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__close_with_no_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
                review_batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewBatchRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_review_batch_api_project_workspaces__project_workspace_id__review_batches__review_batch_id__import_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
                review_batch_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ImportReviewBatchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
