/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/project-workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Project Workspaces */
        get: operations["list_project_workspaces_api_project_workspaces_get"];
        put?: never;
        /** Create Project Workspace */
        post: operations["create_project_workspace_api_project_workspaces_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/project-workspaces/{project_workspace_id}/purchase-lines": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project Workspace Purchase Lines */
        get: operations["get_project_workspace_purchase_lines_api_project_workspaces__project_workspace_id__purchase_lines_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ProjectWorkspaceCreate */
        ProjectWorkspaceCreate: {
            /** Project Name */
            project_name: string;
            /** Project Type */
            project_type: string;
            /** Location */
            location: string;
            /** Completion Date */
            completion_date?: string | null;
            /** Completion Year */
            completion_year?: number | null;
            /** Floor Area */
            floor_area?: string | null;
            /** Trade Scopes */
            trade_scopes?: string[];
            /** Client Or Owner */
            client_or_owner?: string | null;
            /** Notes */
            notes?: string | null;
        };
        /** ProjectWorkspaceList */
        ProjectWorkspaceList: {
            /** Items */
            items: components["schemas"]["ProjectWorkspaceListItem"][];
        };
        /** ProjectWorkspaceListItem */
        ProjectWorkspaceListItem: {
            /** Id */
            id: number;
            /** Project Name */
            project_name: string;
        };
        /** ProjectWorkspacePurchaseLinesView */
        ProjectWorkspacePurchaseLinesView: {
            project_workspace: components["schemas"]["ProjectWorkspaceListItem"];
            /** Items */
            items: unknown[];
        };
        /** ProjectWorkspaceRead */
        ProjectWorkspaceRead: {
            /** Project Name */
            project_name: string;
            /** Project Type */
            project_type: string;
            /** Location */
            location: string;
            /** Completion Date */
            completion_date?: string | null;
            /** Completion Year */
            completion_year?: number | null;
            /** Floor Area */
            floor_area?: string | null;
            /** Trade Scopes */
            trade_scopes?: string[];
            /** Client Or Owner */
            client_or_owner?: string | null;
            /** Notes */
            notes?: string | null;
            /** Id */
            id: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_project_workspaces_api_project_workspaces_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectWorkspaceList"];
                };
            };
        };
    };
    create_project_workspace_api_project_workspaces_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectWorkspaceCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectWorkspaceRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_workspace_purchase_lines_api_project_workspaces__project_workspace_id__purchase_lines_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_workspace_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectWorkspacePurchaseLinesView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
